import type { Event } from "./types";
import { addHours, addDays, formatISO } from "date-fns";

const now = new Date();

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Indie Music Showcase",
    description:
      "Discover the best of Bangalore's indie music scene. An evening of live performances from up-and-coming artists. Refreshments available.",
    address: "100 Feet Road, Indiranagar, Bengaluru, Karnataka 560038",
    date: formatISO(addHours(now, 1)),
    tags: ["Music", "Live", "Indie"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "music concert",
  },
  {
    id: "2",
    title: "Startup Founders Meetup",
    description:
      "Network with fellow entrepreneurs, investors, and innovators. Share your ideas, learn from experts, and build valuable connections.",
    address: "WeWork, EPIP Zone, Whitefield, Bengaluru, Karnataka 560066",
    date: formatISO(addHours(now, 2.5)),
    tags: ["Tech", "Networking", "Business"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "business meeting",
  },
  {
    id: "3",
    title: "Open Mic Comedy Night",
    description:
      "Laugh your heart out with the city's funniest comedians. Sign up for a slot if you're feeling brave!",
    address: "80 Feet Road, Koramangala 4th Block, Bengaluru, Karnataka 560034",
    date: formatISO(addHours(now, 5)),
    tags: ["Comedy", "Open Mic", "Entertainment"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "comedy club",
  },
  {
    id: "4",
    title: "Artisan Farmers Market",
    description:
      "Shop for fresh, organic produce, handmade goods, and delicious treats directly from local farmers and artisans.",
    address: "Palace Grounds, Jayamahal Main Rd, Bengaluru, Karnataka 560006",
    date: formatISO(addDays(now, 1)),
    tags: ["Market", "Food", "Local"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "farmers market",
  },
  {
    id: "5",
    title: "Digital Art Exhibition",
    description: "Explore the intersection of technology and creativity in this stunning exhibition of digital art from local and international artists.",
    address: "MG Road, Shanthala Nagar, Ashok Nagar, Bengaluru, Karnataka 560001",
    date: formatISO(addDays(now, 2)),
    tags: ["Art", "Tech", "Exhibition"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "art gallery",
  },
  {
    id: "6",
    title: "Yoga in the Park",
    description: "Start your weekend with a rejuvenating morning yoga session in the serene surroundings of Cubbon Park. All levels welcome.",
    address: "Cubbon Park, Kasturba Road, Bengaluru, Karnataka 560001",
    date: formatISO(addDays(now, 3)),
    tags: ["Wellness", "Yoga", "Outdoors"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "yoga park",
  },
  {
    id: "7",
    title: "Bangalore Tech Summit 2024",
    description: "A premier tech conference featuring keynote speakers, panel discussions, and workshops on the latest trends in AI, blockchain, and cloud computing.",
    address: "Bangalore International Exhibition Centre (BIEC), 10th Mile, Tumkur Road, Bengaluru, Karnataka 562123",
    date: formatISO(addDays(now, 10)),
    tags: ["Tech", "Conference", "AI"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "tech conference",
  },
  {
    id: "8",
    title: "Street Food Festival",
    description: "A gastronomic delight! Sample the best street food from all over India, right here in Bangalore. Live music and entertainment.",
    address: "VV Puram Food Street, Visveswarapuram, Basavanagudi, Bengaluru, Karnataka 560004",
    date: formatISO(addDays(now, 4)),
    tags: ["Food", "Festival", "Culture"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "food festival",
  },
  {
    id: "9",
    title: "Classic Movie Marathon",
    description: "Join us for a nostalgic trip down memory lane with a marathon of classic Hollywood movies. Popcorn and drinks on the house!",
    address: "PVR Cinemas, Orion Mall, Dr Rajkumar Rd, Rajajinagar, Bengaluru, Karnataka 560055",
    date: formatISO(addDays(now, 5)),
    tags: ["Movies", "Entertainment", "Retro"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "movie theater",
  },
  {
    id: "10",
    title: "Photography Workshop",
    description: "Learn the art of photography from a professional. This workshop covers everything from basics to advanced techniques. Bring your own camera.",
    address: "Lalbagh Botanical Garden, Mavalli, Bengaluru, Karnataka 560004",
    date: formatISO(addDays(now, 6)),
    tags: ["Workshop", "Photography", "Art"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "camera lens",
  },
  {
    id: "11",
    title: "Live Jazz Night",
    description: "Unwind with some smooth jazz and fine wine. A perfect evening for music lovers.",
    address: "Windmills Craftworks, 331, 5B Road, EPIP Zone, Whitefield, Bengaluru, Karnataka 560066",
    date: formatISO(addDays(now, 7)),
    tags: ["Music", "Jazz", "Live"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "jazz club",
  },
  {
    id: "12",
    title: "Book Club Meeting",
    description: "Discuss this month's book, 'The Midnight Library' by Matt Haig. New members are always welcome.",
    address: "Atta Galatta, 178, 5th Main, 9th Cross, 1st Stage, Indiranagar, Bengaluru, Karnataka 560038",
    date: formatISO(addDays(now, 8)),
    tags: ["Books", "Community", "Literature"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "books library",
  },
  {
    id: "13",
    title: "Electronic Dance Music Party",
    description: "Dance the night away to the beats of top DJs. Get ready for an electrifying experience with stunning visuals and sound.",
    address: "Pebble The Jungle Lounge, #3, Ramana Maharishi Road, Palace Grounds, Sadashivanagar, Bengaluru, Karnataka 560080",
    date: formatISO(addDays(now, 9)),
    tags: ["Music", "Party", "EDM"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "dj concert",
  },
  {
    id: "14",
    title: "Poetry Slam",
    description: "A stage for poets and spoken word artists to share their creations. Come to perform or just to listen.",
    address: "Urban Solace, 32, Annaswamy Mudaliar Road, Bengaluru, Karnataka 560042",
    date: formatISO(addDays(now, 11)),
    tags: ["Poetry", "Performance", "Art"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "poetry slam",
  },
  {
    id: "15",
    title: "Gardening Workshop",
    description: "Learn how to create your own urban garden. We'll cover soil, seeds, and care for your plants. All materials provided.",
    address: "GreenMyLife, 4th Cross, 2nd Main Road, Domlur II Stage, Bengaluru, Karnataka 560071",
    date: formatISO(addDays(now, 12)),
    tags: ["Workshop", "Gardening", "DIY"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "potted plants",
  },
  {
    id: "16",
    title: "Historical Walking Tour",
    description: "Explore the rich history of Bangalore's Pete area with our guided walking tour.",
    address: "Bangalore Fort, New Tharagupet, Bengaluru, Karnataka 560002",
    date: formatISO(addDays(now, 13)),
    tags: ["History", "Tour", "Culture"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "historic building",
  },
  {
    id: "17",
    title: "Board Games Evening",
    description: "Join us for an evening of strategy and fun with a wide variety of board games. From Catan to Cards Against Humanity, we have it all.",
    address: "Victory Point, 3rd Floor, 18, 17th Main Rd, KHB Colony, 5th Block, Koramangala, Bengaluru, Karnataka 560095",
    date: formatISO(addDays(now, 14)),
    tags: ["Games", "Social", "Community"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "board game",
  },
  {
    id: "18",
    title: "Salsa Dance Social",
    description: "Learn the basics of Salsa and then dance the night away with fellow enthusiasts. No partner required.",
    address: "La Rumba, 5th Floor, 12, Magrath Road, Above GKB Opticals, Bengaluru, Karnataka 560025",
    date: formatISO(addDays(now, 15)),
    tags: ["Dance", "Salsa", "Social"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "dancing couple",
  },
  {
    id: "19",
    title: "AI & Machine Learning Meetup",
    description: "A meetup for AI enthusiasts and professionals to discuss the latest advancements in Machine Learning.",
    address: "WeWork, Galaxy, 43, Residency Road, Shanthala Nagar, Ashok Nagar, Bengaluru, Karnataka 560025",
    date: formatISO(addDays(now, 16)),
    tags: ["Tech", "AI", "Networking"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "artificial intelligence",
  },
  {
    id: "20",
    title: "Pottery Making Class",
    description: "Get your hands dirty and learn the basics of pottery. Create your own masterpiece to take home.",
    address: "Claytopia, 11, 80 Feet Road, Koramangala 1st Block, Bengaluru, Karnataka 560034",
    date: formatISO(addDays(now, 17)),
    tags: ["Art", "Workshop", "Craft"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "pottery wheel",
  },
  {
    id: "21",
    title: "Cycling Adventure to Nandi Hills",
    description: "An early morning cycling trip to the beautiful Nandi Hills. Enjoy the sunrise and a rewarding breakfast at the top.",
    address: "Nandi Hills, Karnataka 562103",
    date: formatISO(addDays(now, 18)),
    tags: ["Outdoors", "Cycling", "Adventure"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "hills sunrise",
  },
  {
    id: "22",
    title: "Wine Tasting Experience",
    description: "A guided tour of a local vineyard followed by a wine tasting session. Learn about the art of winemaking.",
    address: "Grover Zampa Vineyards, 63, Raghunathapura, Devanahalli Road, Bengaluru, Karnataka 562110",
    date: formatISO(addDays(now, 19)),
    tags: ["Food", "Wine", "Experience"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "wine glasses",
  },
  {
    id: "23",
    title: "Theatre Play: 'The Mousetrap'",
    description: "Experience Agatha Christie's classic murder mystery live on stage. A thrilling performance by a talented local troupe.",
    address: "Ranga Shankara, 36/2, 8th Cross Rd, R K Colony, 2nd Phase, J. P. Nagar, Bengaluru, Karnataka 560078",
    date: formatISO(addDays(now, 20)),
    tags: ["Theatre", "Drama", "Entertainment"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "theater stage",
  },
  {
    id: "24",
    title: "Bangalore Comic Con",
    description: "The city's biggest pop culture event is back! Meet artists, buy merchandise, and cosplay as your favorite characters.",
    address: "KTPO, Whitefield, Bengaluru, Karnataka 560066",
    date: formatISO(addDays(now, 21)),
    tags: ["Comic Con", "Pop Culture", "Cosplay"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "comic books",
  },
  {
    id: "25",
    title: "Sustainable Living Workshop",
    description: "Learn practical tips and tricks for a more sustainable lifestyle. Topics include zero-waste, composting, and upcycling.",
    address: "The Courtyard Community, 105, KH Road, Lalbagh Double Road, Shanti Nagar, Bengaluru, Karnataka 560027",
    date: formatISO(addDays(now, 22)),
    tags: ["Workshop", "Sustainability", "Eco-friendly"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "sustainable living",
  },
  {
    id: "26",
    title: "Karaoke Night",
    description: "Sing your favorite songs and be a star for a night. A fun-filled evening for everyone.",
    address: "Gilly's Restobar, 91, Jyoti Nivas College Road, 5th Block, Koramangala, Bengaluru, Karnataka 560095",
    date: formatISO(addDays(now, 23)),
    tags: ["Music", "Karaoke", "Social"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "karaoke microphone",
  },
  {
    id: "27",
    title: "Baking Masterclass: Sourdough Bread",
    description: "Master the art of making delicious sourdough bread from scratch in this hands-on baking class.",
    address: "Lavonne Academy of Baking Science and Pastry Arts, 2nd Phase, 263, 3rd Main Rd, Stage 2, Domlur, Bengaluru, Karnataka 560071",
    date: formatISO(addDays(now, 24)),
    tags: ["Food", "Workshop", "Baking"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "sourdough bread",
  },
  {
    id: "28",
    title: "Flea Market Finds",
    description: "Browse through a curated collection of vintage clothes, quirky decor, and handmade crafts at this popular flea market.",
    address: "Sunday Soul Sante, Jayamahal Palace Hotel, Jayamahal Main Road, Bengaluru, Karnataka 560006",
    date: formatISO(addDays(now, 25)),
    tags: ["Market", "Shopping", "Vintage"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "flea market",
  },
  {
    id: "29",
    title: "Indian Classical Music Concert",
    description: "A mesmerizing evening of Indian classical music featuring renowned artists.",
    address: "Chowdiah Memorial Hall, 16th Cross, G.D. Park Extension, 2nd Main Road, Malleswaram, Bengaluru, Karnataka 560003",
    date: formatISO(addDays(now, 26)),
    tags: ["Music", "Classical", "Culture"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "sitar instrument",
  },
  {
    id: "30",
    title: "Rock Climbing for Beginners",
    description: "Learn the ropes of rock climbing at this introductory session. All safety gear will be provided.",
    address: "Equilibrium Climbing Station, 606, 6th floor, Devatha Plaza, Residency Rd, Bengaluru, Karnataka 560025",
    date: formatISO(addDays(now, 27)),
    tags: ["Adventure", "Sports", "Climbing"],
    imageUrl: "https://placehold.co/600x400.png",
    "data-ai-hint": "rock climbing",
  },
];
